# Intro to python 

Welcome to Google Colaboratory, we will use this framework to ease up the execution of the notebooks presented in the classes of Astrophysics Lab. 
For more info about CoLab, plese look at [this tutorial](https://colab.research.google.com/#scrollTo=-Rh3-Vt9Nev9). 

# Lesson 0. Utilities of Numpy  

The library `numpy` is one of the most important   python modules to deal with python arrays and matrices.  
Let's see how a vector with  `N=100` elements is initialized. 


In [1]:
import numpy as np
import pylab as pl 

In [2]:
N=100 
v= np.zeros(N, dtype=np.float_) 
print(v, type(v),)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.] <class 'numpy.ndarray'>


`v` is a `class`  object, employing several `attributes` and functionalities. like :  

In [3]:
v+= np.arange(N) 

print(  v.size, v.min(), v.mean(), v.std(), v.argmin(), v.argmax()  )

100 0.0 49.5 28.86607004772212 0 99


please check the  [numpy documentation](https://numpy.org/) for more details.  Matrices can be initialized similarly . 
 

In [4]:
A = np.matrix( [[1,0,3],[0,4,5],[2,3,0]]) 
print (A)
print (f"A is a {A.shape} matrix"  )
print(f"determinant :{np.linalg.det(A)}")


[[1 0 3]
 [0 4 5]
 [2 3 0]]
A is a (3, 3) matrix
determinant :-38.99999999999999


# Linear systems 

we can solve linear system easily , together with finding the eigenvalues and eigenvectors of $A$ 

In [5]:
b= np.ones(3)

x= np.linalg.solve(A, b)

print(f"solution of Ax = b, x={x}" )
print("check whether Ax -b =0 ", A.dot(x) - b)


lambdas, W= np.linalg.eig(A,  )
Adiag= np.diag(lambdas)
print("diagonal form of A:\n", Adiag    ) 

solution of Ax = b, x=[0.46153846 0.02564103 0.17948718]
check whether Ax -b =0  [[0. 0. 0.]]
diagonal form of A:
 [[-3.39410744  0.          0.        ]
 [ 0.          1.72222899  0.        ]
 [ 0.          0.          6.67187845]]


In [6]:
print( "Check that Aw = lambda w\nw0",
      A.dot(W[:,0]) - lambdas[0]* (W[:,0]), "\nw1",
A.dot(W[:,1]) - lambdas[1]* (W[:,1]), "\nw2",
A.dot(W[:,2]) - lambdas[2]* (W[:,2])) 

Check that Aw = lambda w
w0 [[ 8.88178420e-16]
 [-6.66133815e-16]
 [ 1.33226763e-15]] 
w1 [[ 4.44089210e-16]
 [ 3.33066907e-16]
 [-4.44089210e-16]] 
w2 [[ 1.11022302e-15]
 [-8.88178420e-16]
 [ 2.22044605e-15]]


## Integration and differentiation 


assume we have a function, 
$f(x) = 2x^3 + e^{-3x}$, and we wanna estimate the derivative and the integral. 
We can use _symbolic python_,  `sympy` to do the heavy lifting to  calulate and estimate'em  with the funcion `lambdify`. 



In [7]:
import scipy
from scipy.integrate import quad 
import sympy 
from sympy import lambdify
from sympy.abc import x

ModuleNotFoundError: No module named 'sympy'

In [ ]:
f= 2*x**3 + sympy.exp(-3*x )
# now the function becomes from symbolic to a real function written in python code 
func= lambdify(x, f )
# it's implementation should be exactly the same as the following lines of code: 
def function (x): 
    return 2*x**3 + np.exp(-3*x) 

In [ ]:
xvalues= np.linspace(-1,1,128 )
pl.plot(xvalues, function(xvalues), lw=2, label='f implemented')
pl.plot(xvalues, func(xvalues),lw=6, alpha=.5 ,label='f lambdified')
pl.plot(xvalues,function(xvalues) -func(xvalues), label='difference' )
pl.legend() 

Estimating derivatives and integral is as simple as this: 


In [ ]:
print("f(x)= ",f   )
print("df/dx= ",f.diff()  )
print("integral[f dx] = ",f.integrate()  )


Thus we can even lambdify the primitive functions, $F$ to estimate the definite integral : 
$$
F(b)- F(a) = \int_a^b f dx
$$
we'll consider $a=-1$ and $b=1$

In [ ]:
prim_func= lambdify(args=x, expr= f.integrate()  )
a=-1
b=1
print("Definite integral" , prim_func(b) - prim_func(a))

this result should be about the same as  the one obtained with `np.trapz` and to `scipy.integrate.quad`. We 'll show the different usage in the following: 

In [ ]:
int_np =np.trapz(y= func(xvalues), x=xvalues )
print("Trapezoidal rule (numpy):",int_np)

int_sp =quad(function, a=-1, b=1 )
print("Quadrature rule (scipy):",int_sp)

for the latter the second value returned is the error associated to the estimate. 

## Best-Fit   using `scipy.optimize.curve_fit`

let's assume we've data distributed with a Normal distribution and we want to fit the Gaussian curve associated to it. 
We will use `curve_fit` to do this. We firstly generate our fake data set with random numbers normally distributed: 

In [ ]:
import scipy 
from scipy.optimize import curve_fit 

In [ ]:

xvalues = np.random.normal(loc=0, scale=4, size=1000)


we will estimate the  histogram (normalized to 1), now the frequency $y$ in each bin $x$ correspond to our data we wanna fit, we also  associate fake error bars  to the measurements $y$,  $1\%$ error bars .

In [ ]:

y, edges  = pl.histogram(xvalues, bins=20, density=True  )
yerr=np.ones_like(y)*0.01
xbins = np.array([.5*(edges[i+1] + edges[i] ) for i in range(y.size )]) 
pl.errorbar( xbins, y,yerr= yerr , fmt='o'  )



let's make the assumption now that the model  function is a gaussian , parametrized by 3 parameters, $A,
\mu, \sigma$ 

In [ ]:
gaussian = lambda x,A ,  mu,sigma: A* np.exp(-(x-mu)**2/2/(sigma**2 ))


estimate the best- fit  parameters

In [ ]:
bestfit_params,covariances_params= curve_fit(gaussian, xbins, y ,sigma= yerr)

In [ ]:
print((covariances_params)) 

In [ ]:
pl.errorbar( xbins, y,yerr= yerr , fmt='o', label='data'  )
pl.plot( xbins, gaussian(xbins,*bestfit_params), label='best-fit' )
pl.legend() 
pl.grid()



## Finding the roots  

Another useful think  is to find the zeros of a function, e.g.  
 
$f(x_s) =  x - \log {3x}=0 $

let's find $x_s$ such that: 

$ x_s= \log {3x_s}$


In [ ]:
from scipy.optimize import root_scalar

In [ ]:
def f(x): 
    return x -  np.log(3*x) 

xvalues= np.linspace(1e-6,2,128 )
pl.plot(xvalues, f(xvalues))
pl.grid()

s= root_scalar(f,  bracket=[1e-4, 1], method='brentq')
pl.scatter (s.root,f(s.root), marker='o'  ) 
pl.ylim(-1,2)
print(s)
s= root_scalar(f,  bracket=[ 1,2], method='brentq')
pl.scatter (s.root,f(s.root), marker='o'  ) 

